### PR TITLE
Example extension with all the .args files

### PR DESCRIPTION
**Pull request by rin-st**
Mentioined in this issue https://github.com/scaffold-eth/create-eth/issues/140

Extension with all the .args files + additional files for giving best understanding how extension should be structured

Hardhat/foundry contracts taken from erc20 extension + added tests

If we're planning to merge this extension, it will be much easier to update and maintain [TEMPLATING-FILES.md](https://github.com/scaffold-eth/create-eth/commit/6536ab714eb57f4cc1ad5a21fffc23b5ff29bc92) 

To test:

```
yarn cli -e scaffold-eth/create-eth-extensions:example-init
```

TODOS:
- [x] update readme
- [ ] update [TEMPLATING-FILES.md](https://github.com/scaffold-eth/create-eth/commit/6536ab714eb57f4cc1ad5a21fffc23b5ff29bc92) (after merging this PR)

### CODE REVIEW

**Comment by carletex** [comment]
I think this is great, Rinat! Thank you.

https://github.com/scaffold-eth/create-eth/pull/174 + https://github.com/scaffold-eth/create-eth/pull/175 + the exploration of a new template engine (like EJS):  do we want to wait in case we do breaking changes? Merging and use it as a test (+ see the breaking changes) is also a good option.

What do you guys think?

**Comment by rin-st** [comment]
I think we don't need to wait

- we can update TEMPLATE-FILES.md right now + add actual information
- research + merge could take weeks. After merging new updates it will be easy to update this extension
- > Merging and use it as a test (+ see the breaking changes) is also a good option.

**Comment by damianmarti** [comment]
This is great @rin-st! Thanks!!

Yeah, I think we can merge it now and then update this example when we make all the other changes.

The package.json files are missing. I think it will be nice to add these too.

**Comment by rin-st** [comment]
> The package.json files are missing. I think it will be nice to add these too.

Thanks Damu! Waiting for https://github.com/scaffold-eth/create-eth/pull/181

**Comment by rin-st** [comment]
> The package.json files are missing. I think it will be nice to add these too.

Added!

**Review by technophile-04 — COMMENTED** [review]
Thanks @rin-st! 

List of files I think we missed: 

- `next.config.args.mjs`
- `getMetadata.ts.args.mjs`
- NextJs - `.env.example.args.mjs`

Also we need to update `TEPLATING-FILES.md` in create-eth. And maybe add section a in Contributing.md too that whenever we add new `.template.mjs` file we update this branch in `create-eth-extension` with example `.args.mjs` file and update `TEMPLATING-FILES.md` too

**Comment by rin-st** [comment]
> next.config.args.mjs
> getMetadata.ts.args.mjs
> NextJs - .env.example.args.mjs

Thanks Shiv, good eye! Added also foundry Makefile args since template was added here https://github.com/scaffold-eth/create-eth/pull/182/files

> Also we need to update TEPLATING-FILES.md in create-eth. And maybe add section a in Contributing.md too that whenever we add new .template.mjs file we update this branch in create-eth-extension with example .args.mjs file and update TEMPLATING-FILES.md too

https://github.com/scaffold-eth/create-eth/pull/185

**Review by damianmarti — APPROVED** [review]
It's working great and it seems like we are not missing anything.

Thanks @rin-st !!

**Review by technophile-04 — APPROVED** [review]
Thanks @rin-st 🙏 This is awesome! We covered all the imp arg variables in all args file. 

Also `yarn chain, deploy, start` works nicely along with `yarn next:checkt-types, next:lint`


---

Just for future thinking of using this extension for create-eth CI tests we will need all customisation of `onlyLocalBurnerWallet` in scaffold.config.ts so that we could test faucet and all the workflow with cypress or playright 

But for now  this extension unlocks doing `yarn chain, deploy, start, next:lint, next:check-types` in create-eth CI 🙌

**Pull request merged**
